language: cpp
dist: trusty
sudo: required
branches:
  only:
  - master
  - /\d+\.\d+\.\d+$/
before_install:
- eval "${MATRIX_EVAL}"
- ${CXX} --version
- openssl aes-256-cbc -K $encrypted_eba2f7543984_key -iv $encrypted_eba2f7543984_iv
  -in travis/travisci_builder_id_key.enc -out travis/travisci_builder_id_key -d
- chmod 600 travis/travisci_builder_id_key
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  ccache: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
install: travis/install_extra_deps.sh
script: travis/compile_all.py
after_failure: travis/upload_all_log.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: travis/deploy.sh
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: travis/deploy.sh
    on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE = cron
env:
  global:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  matrix:
    - PLATFORM="native_dyn"
    - PLATFORM="native_static"
    - PLATFORM="win32_dyn"
    - PLATFORM="win32_static"
    - PLATFORM="armhf_dyn"
    - PLATFORM="armhf_static"
    - PLATFORM="i586_dyn"
    - PLATFORM="i586_static"
    - PLATFORM="android_arm"
    - PLATFORM="android_arm64"
    - PLATFORM="android_x86"
    - PLATFORM="android_x86_64"
matrix:
  allow_failures:
    - env: PLATFORM="android_arm"
    - env: PLATFORM="android_arm64"
    - env: PLATFORM="android_mips"
    - env: PLATFORM="android_mips64"
    - env: PLATFORM="android_x86"
    - env: PLATFORM="android_x86_64"
  include:
    - env: PLATFORM="android_mips"
      if: type!=cron AND type!=pull_request
    - env: PLATFORM="android_mips64"
      if: type!=cron AND type!=pull_request

notifications:
  irc:
    channels:
     - "chat.freenode.net#kiwix"
    on_success: change
    on_failure: always
addons:
  ssh_known_hosts:
  - download.kiwix.org
  - download.openzim.org
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - python3-pip
      - zlib1g-dev
      - libjpeg-dev
      - libmagic-dev
      - ctpp2-utils
      - libctpp2-dev
      - libmicrohttpd-dev
      - g++-mingw-w64-i686
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-base
      - mingw-w64-tools
      - default-jdk
      - autopoint
      - libc6-dev:i386
      - libstdc++-6-dev:i386
      - gcc-5-multilib
      - g++-5-multilib
