name: Build Base

on: [push]

env:
  DOCKER_VERSION: 25

jobs:
  Docker:
    strategy:
      fail-fast: false
      matrix:
        variant: [xenial, bionic, f30, focal]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      shell: bash
      run: |
        TAGNAME=${{matrix.variant}}-${DOCKER_VERSION}
        if [ ! $(curl -sflL https://hub.docker.com/v2/repositories/kiwix/kiwix-build_ci/tags/${TAGNAME}) ]
        then
          echo "${{secrets.docker_password}}" | docker login -u "${{secrets.docker_username}}" --password-stdin
          FULLTAGNAME=kiwix/kiwix-build_ci:${TAGNAME}
          docker build -t ${FULLTAGNAME} - < ${GITHUB_WORKSPACE}/.github/ci_images/${{matrix.variant}}_builder.dockerfile
          docker push ${FULLTAGNAME}
        fi

  Linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - native_static
          - native_dyn
          - android_arm
          - android_arm64
          - win32_static
          - win32_dyn
        include:
          - target: native_static
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: native_dyn
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: android_arm
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: android_arm64
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: win32_static
            image_variant: f30
            lib_postfix: '64'
          - target: win32_dyn
            image_variant: f30
            lib_postfix: '64'
    env:
      HOME: /home/runner
      SSH_KEY: /tmp/id_rsa
    runs-on: ubuntu-latest
    needs: Docker
    container:
      image: "kiwix/kiwix-build_ci:${{matrix.image_variant}}-25"
    steps:
    - name: Checkout code
      shell: bash
      run: |
        cd $HOME
        git clone https://github.com/${REP} --depth=1 --branch ${GITHUB_REF##*/}
        pip3 install --user --no-deps ./${REP##*/}
      env:
        REP: ${{github.repository}}
    - name: secret
      shell: bash
      run: |
        echo "${{secrets.ssh_key}}" > $SSH_KEY
        chmod 600 $SSH_KEY
    - name: Ensure base deps
      shell: bash
      run: |
        cd $HOME
        kiwix-build/.github/scripts/ensure_base_deps.py
      env:
        PLATFORM_TARGET: ${{matrix.target}}
